### ISSUE TITLE
Scoring-up not automatically running for me

### ISSUE THREAD

**Issue by karend27** [MeasuringPolyphony/mp_editor#12]
When I did all the data entry and moved to the score editor, I tried to add a dot like Martha showed in her video she sent me: I was able to add the dot, but the scoring-up did not automatically run again. Is there something else I should do?

**Comment by JRegimbal** [comment]
That's odd. The function to run the scoring up appears to be running when dots are added for me. Could you give me more information?

**Comment by karend27** [comment]
I'm using Google Chrome on my iMac. I entered all the pitches and text for the piece we've been working on and then clicked to move to scoring up. It all lined up as I would expect. I then clicked the pitch that needed the dot added, and it added the dot but nothing else happened. I can add a screen shot if it's helpful.

**Comment by JRegimbal** [comment]
That would be helpful thank you! I'll try and replicate it on my computer and see if I can figure out what's going on.

**Comment by karend27** [comment]
This actually now seems to be working for me, so I will close this issue for now.
