### ISSUE TITLE
Score editor sometimes disappears

### ISSUE THREAD

**Issue by JRegimbal** [MeasuringPolyphony/mp_editor#13]
The score editor SVG sometimes disappears after a few editing actions. It is unclear why this occurs at the time of writing.

**Comment by JRegimbal** [comment]
@martha-thomae Is there any extra info you could tell me about how to replicate this? I'm unable to figure out a small example on my computer.

**Comment by martha-thomae** [comment]
I can send you the <parts>-based file I was working on when this happened. In the last part of the "motetus" there is a group of semibreves (5 semibreves + a dot + 2 semibreves). What I did was:
1. I added another dot between the third and fourth semibreve.
![1A - Semibreve to modify](https://user-images.githubusercontent.com/13948831/77356112-18c07780-6d1c-11ea-95ca-ea5df7e89d5f.png)
(The alignment got fixed after this change.)
![1B - re-alignment](https://user-images.githubusercontent.com/13948831/77356113-18c07780-6d1c-11ea-93f7-e3cb99e42e20.png)
2. Then I moved into the breve (square note) preceding all these semibreves and tried to change it to a longa (pressing "9").
![2 Breve to modify to a longa](https://user-images.githubusercontent.com/13948831/77356132-1e1dc200-6d1c-11ea-845b-ee08839dd613.png)
3. Everything went blank afterward.

I did notice that if I tried another set of modifications, this doesn't happen. Let's substitute the breve to modify in step two by one of the semibreves. Everything is fine. I can even do a whole bunch of modifications and then try to modify the "problematic" breve, and everything will be fine.

But still, if I do the steps enumerated above, the result will always be the same (the blank page). No idea why.

[ExamplePartsFile_Fauvel_folio9v.zip](https://github.com/MeasuringPolyphony/mp_editor/files/4371574/ExamplePartsFile_Fauvel_folio9v.zip)

**Comment by martha-thomae** [comment]
Also tried (after step 1 - adding the dot) to make the two breves into semibreves. 
![2A - breves to change](https://user-images.githubusercontent.com/13948831/77357660-e49a8600-6d1e-11ea-99ac-6c373100bf0d.png)

Everything was fine. 
![2B - Now they are Semibreves](https://user-images.githubusercontent.com/13948831/77357780-17447e80-6d1f-11ea-955d-897256b29942.png)

But then I tried to add dots between this very-long sequence of semibreves, and the page turns blank again. Here is the place where I tried to add the dot.
![2C - Add dot after this Semibreve](https://user-images.githubusercontent.com/13948831/77357810-23304080-6d1f-11ea-9208-2fb228f89b00.png)

**Comment by martha-thomae** [comment]
@JRegimbal, you can replicate the error by only entering the notes shown in the first screenshot (no need to enter the entire piece). I tried it already.

**Comment by JRegimbal** [comment]
Hi @martha-thomae! I was able to replicate this. The issue is in the `ArsAntiqua.js` file with the issue being `last_uncolored_note` is undefined at line 100.

**Comment by JRegimbal** [comment]
I've edited the score editor to display an alert with a short description of the error in scoring up when one occurs. If you open the console, a more detailed message should be visible.

**Comment by martha-thomae** [comment]
> Hi @martha-thomae! I was able to replicate this. The issue is in the `ArsAntiqua.js` file with the issue being `last_uncolored_note` is undefined at line 100.

Thanks! It seems that I didn't change that line when translating from Python to JavaScript. Thanks so much for taking the time to figure this out.

**Comment by martha-thomae** [comment]
> I've edited the score editor to display an alert with a short description of the error in scoring up when one occurs. If you open the console, a more detailed message should be visible.

I wanted to try this. But for some reason, the page is not loading correctly. I am trying to do "Open Storage" and "load" the music on one of my "slots." After this, the bounding boxes of the staves appear and the voice's metadata (mensuration and label of the voice), but no music is rendered. And when I click on "Save to MEI file" or on "Move to Score Editor", nothing happens.

**Comment by JRegimbal** [comment]
Hmm this might have something to do with me changing the MusicItem object to keep track of a key signature. Could you share if an error appears in the console?

**Comment by martha-thomae** [comment]
Sure!
This is what I see after loading a particular slot:

![1 After load](https://user-images.githubusercontent.com/13948831/77937275-1a40f100-7282-11ea-9073-2b714be08862.png)

And when I try to "move to score editor," I have this extra error:

![2 After clicking on moving to score](https://user-images.githubusercontent.com/13948831/77937313-29c03a00-7282-11ea-9829-a88ac85ecb49.png)

**Comment by JRegimbal** [comment]
Okay I think this is something I can fix. I'll let you know when it should work for you.

**Comment by JRegimbal** [comment]
@martha-thomae it should be working now. Let me know if it isn't!

**Comment by martha-thomae** [comment]
It is working. Thanks!

**Comment by martha-thomae** [comment]
So, going back to:
> I've edited the score editor to display an alert with a short description of the error in scoring up when one occurs. If you open the console, a more detailed message should be visible.

Is it possible to display in which line the error happens? Maybe I am just not understanding the message in the console. I would like to be able to know that this was the issue:
> The issue is in the ArsAntiqua.js file with the issue being last_uncolored_note is undefined at line 100.

Here is my console, I don't see anything that would let me know that the issue "Cannot read property 'hasAttribute' of underfined" (indicated in the dialog box) happened on line 100. This would be really helpful for me to debug. Is it possible just to display the line of the error either in the dialog box or in the console? Thanks! It is really helpful to have everything else being displayed in the console (the note counters).
![Screen Shot 2020-03-30 at 7 03 02 PM](https://user-images.githubusercontent.com/13948831/77970549-77f12f80-72ba-11ea-827d-94099ee143db.png)

**Comment by martha-thomae** [comment]
Perfect! It works :)
Very helpful for debugging

![Screen Shot 2020-03-31 at 5 07 28 PM](https://user-images.githubusercontent.com/13948831/78075447-8d299500-7372-11ea-8f3f-73a3db0e7ee4.png)

**Comment by karend27** [comment]
I think this has also been fixed, and so will close for now.
