### ISSUE TITLE
Deleting clefs

### ISSUE THREAD

**Issue by karend27** [MeasuringPolyphony/mp_editor#14]
I accidentally typed a G at the beginning of a new staff in the data entry mode, and a g clef appeared and I wasn't able to backspace and delete it to enter a c-clef.

**Comment by JRegimbal** [comment]
In data entry? You should be able to keep pressing backspace to get to there. It's possible that the clef was selected and so deleting wasn't possible, but moving the selector to the end of the staff should allow this to happen.

**Comment by karend27** [comment]
I'm going to close this for the moment, because I haven't been able to replicate it, and it may be sort of related anyway to the other clef bug that is open right now.
