### ISSUE TITLE
Adding key signature

### ISSUE THREAD

**Issue by karend27** [MeasuringPolyphony/mp_editor#15]
After you add the clef, how do you add a key signature (in this repertory ths frequent key signature will be one flat).

**Comment by JRegimbal** [comment]
I've added a basic tool to add a key signature. From the input editor after adding a clef, press `k` following by the pitch and accidental to add to the key signature. To remove it, enter the keys again. So to add F# to the key signature, you would add a clef and enter `kf#`. Does this work?

**Comment by karend27** [comment]
Works perfectly!! Thanks!
