### ISSUE TITLE
Sometimes a rest instead of a clef is getting stored in the data entry

### ISSUE THREAD

**Issue by karend27** [MeasuringPolyphony/mp_editor#17]
I've noticed this sometimes happens (and I haven't quite figured out the conditions that replicate it) but here you see at the beginning of the second stave in the triplum, the clef is not being stored properly, and a rest instead, so first of all the pitches are then wrong and the rhythms are off by a breve. This is what it looks like in data entry:
<img width="1288" alt="Screen Shot 2020-04-07 at 9 31 04 AM" src="https://user-images.githubusercontent.com/11195203/78675247-c30ad400-78b2-11ea-8427-50ba77725526.png">
And this is what it looks like in the score editor:
<img width="1221" alt="Screen Shot 2020-04-07 at 9 30 38 AM" src="https://user-images.githubusercontent.com/11195203/78675274-cdc56900-78b2-11ea-99ef-5f94c9e1dc28.png">

**Comment by JRegimbal** [comment]
This may be related to an empty staff being hidden somewhere and putting in the default rest. I've set up the editor to filter out empty staves (signified by no notes being added) from the MEI file that's generated for the score editor. Please let me know if this problem occurs again!

**Comment by karend27** [comment]
I'll close this for now, as it has not happened again recently. Can always reopen if reoccurs.
