### ISSUE TITLE
Ligature keystroke not functioning

### ISSUE THREAD

**Issue by karend27** [MeasuringPolyphony/mp_editor#2]
Help section indicates ligature is made by typing a [ directly after typing pitch and closing the ligature by typing ] directly after last note of ligature. Typing [ seems instead to turn a semibreve into a breve.

**Comment by JRegimbal** [comment]
Looking at the MEI file being generated, the duration of the notes remain as they should be even though the rendering shows them as a breve. (Snippet below)
```
<ligature xml:id="m-7c8131df-cc1e-4a2b-9723-052894a1ee96">
  <note xml:id="m-60d52e98-437b-4c5c-8224-0318e44cd7da" dur="semibrevis" oct="4" pname="c"/>
  <note xml:id="m-7793aa0b-95c7-4438-9d89-1e7367fae677" dur="semibrevis" oct="3" pname="b"/>
  <note xml:id="m-7847feba-cd41-42fe-b976-01baf98bf838" dur="semibrevis" oct="3" pname="a"/>
</ligature>
<note xml:id="m-437e678b-962e-4449-bce8-d3b3e21b378f" dur="semibrevis" oct="3" pname="a"/>
<note xml:id="m-03995ec1-65e2-48e4-9709-c14abab1a7f5" dur="semibrevis" oct="3" pname="b"/>
```
This might be an issue with Humdrum/Verovio.

**Comment by martha-thomae** [comment]
I agree. This is how ligatures are rendered in Verovio (as to square notes close together, regardless of the actual value of the note).
