### ISSUE TITLE
Enhancements to score editor screen

### ISSUE THREAD

**Issue by karend27** [MeasuringPolyphony/mp_editor#20]
Can we add these features to the score editor screen?
- a play/pause button that would play the midi (could be helpful in finding pitch errors in the scored-up version)
- a radio button that would switch between Original Clefs and Modern Clefs?
- a Help Tab like we have on the data entry screen (I can write the content for this)

**Comment by JRegimbal** [comment]
I'll have to look into the first two features, but the help tab is definitely doable. Could you give me an idea of what contents should be there?

**Comment by karend27** [comment]
**Making simple edits**
When you click on pitch, the staff to which that pitch belongs will be highlighted with a square dashed box in the manuscript image in the left of the screen. This will help you check the accuracy of your data entry as you make edits. You can make simple edits directly on the score as follows, by clicking on a pitch to highlight it:
_Pitch_ - Use up/down arrows to change the pitch.
_Rhythm_ - Type a number key to alter its rhythm (1 semibreve, 2 minim, 4 semiminim, 8 fusa, 6 semifusa, 0 breve, 9 long, 7 maxima). The scoring-up of the parts will automatically rerun each time a rhythmic value is changed.
_Dots_ - To add a dot, click on a pitch to highlight it, and type a dot. The dot will be added after this pitch, and the scoring-up of the parts will automatically rerun. To remove a dot, click on the pitch to which the dot is appended and type a dot. The dot will be removed, and the scoring-up of the parts will automatically rerun.
_Accidentals_ - To add or remove a flat, type "b"; to add/remove a sharp, type "#"; to add/remove a natural, type "n".

You can also use the back button to make more significant edits, however, keep in mind, if you return to the data input screen, any changes you have made in the score editor screen will be lost. 

The purpose of the score editor is to do enough editing to enable the correct alignment of the score, and to edit while viewing the manuscript images. For more fine-grained editing of the MEI file, it is recommended that you download the MEI file and open it in a tool that allows you to directly edit the MEI, such as Verovio Humdrum Viewer (https://verovio.humdrum.org/) or the Verovio Editor (https://editor.verovio.org/).

**Comment by JRegimbal** [comment]
Help tab added to the score editor in commit 105447d.

**Comment by karend27** [comment]
The functions for playing the midi files (via Verovio toolkit) are at the bottom of this page in the Measuring Polyphony project files. 
https://github.com/MeasuringPolyphony/measuring_polyphony_jekyll/blob/master/_layouts/display.html

**Comment by karend27** [comment]
And this is the page that has some documentation on the midi player: https://github.com/rism-ch/midi-player/blob/master/README.md#midi-instruments

**Comment by karend27** [comment]
I'm going to close this for now - can reopen if it becomes a highly requested enhancement.
