### ISSUE TITLE
Breaks when accidentally add a rest to a ligature

### ISSUE THREAD

**Issue by karend27** [MeasuringPolyphony/mp_editor#24]
In the following data entry, I had begun a ligature and forgot to close it by typing ']' I then typed 'r' for rest, realized my mistake and tried to backspace and type ']' but it wouldn't let me backspace to delete the last note or do anything.
<img width="1848" alt="Screen Shot 2020-04-15 at 9 22 26 AM" src="https://user-images.githubusercontent.com/11195203/79342696-73a05580-7efb-11ea-91aa-e4c90a624080.png">

**Comment by JRegimbal** [comment]
This is largely an issue with entering ligatures the way we do now. Keeping the tag essentially open until manually closed opens up a lot of possibilities for accidents like this to occur that crash Verovio. I'm trying to think of an alternative way of entering ligatures that doesn't have the same problem.

**Comment by karend27** [comment]
Great - this seems to work. I tried entering a rest and I got a popup telling me that I can't do that and so I then entered the keystroke to close a ligature and proceeded as normal. Thanks!
