### ISSUE TITLE
Previous piece gets appended to new piece

### ISSUE THREAD

**Issue by karend27** [MeasuringPolyphony/mp_editor#28]
When I was testing data entry today, I started a new piece in a new manuscript (but within the same browser window I had already been using). When I was finished the data entry I saw that the old piece was appended at the end of the new piece I entered. Attaching a screenshot and the console file. Old piece had text, whereas I didn't bother adding text to the new piece I was working on.
[measuringpolyphony.github.io-1586980243213.log](https://github.com/MeasuringPolyphony/mp_editor/files/4483438/measuringpolyphony.github.io-1586980243213.log)
<img width="1591" alt="Screen Shot 2020-04-15 at 3 51 49 PM" src="https://user-images.githubusercontent.com/11195203/79382318-571f1000-7f31-11ea-95f4-80a580d28d3d.png">

**Comment by JRegimbal** [comment]
Hmm okay. Perhaps when returning to the manuscript selection screen all the previous data should be cleared?

**Comment by karend27** [comment]
Or perhaps a button somewhere on the interface (maybe that's present on all pages) that says 'Start a new transcription' and if you click it, it returns you to the manuscript selection screen and clears all data?

**Comment by JRegimbal** [comment]
That's a good idea. I've added a start new transcription button that has that behavior.
