### ISSUE TITLE
Clefs are reinserted with each tenor repeat

### ISSUE THREAD

**Issue by karend27** [MeasuringPolyphony/mp_editor#32]
@martha-thomae Currently the clefs seem to be reinserted with each tenor repeat. Can these be taken out? Here's a screenshot of a piece I input and then opened in Verovio humdrum viewer:
<img width="1983" alt="Screen Shot 2020-04-23 at 8 30 05 AM" src="https://user-images.githubusercontent.com/11195203/80099682-dec1db80-853c-11ea-90e9-62f67a0fa972.png">
I'm also attaching the MEI file.
[deafdca5-0b12-4b67-90b0-79c7ab2e145f.xml.zip](https://github.com/MeasuringPolyphony/mp_editor/files/4522471/deafdca5-0b12-4b67-90b0-79c7ab2e145f.xml.zip)

**Comment by martha-thomae** [comment]
Yes, of course. Probably there was a clef change in the original tenor and because the second clef is kept as a `<clef>` element in the stream of notes, it automatically went into the stream of elements cloned. I will filter it out. Thanks, Karen!
