### ISSUE TITLE
Cannot use folio search box after loading previous work 

### ISSUE THREAD

**Issue by zenkuriyama** [MeasuringPolyphony/mp_editor#39]
After going back to the editor to "Load" my previous work, I cannot then use the folio/page search box. 

![Screen Shot 2020-07-28 at 7 02 47 PM](https://user-images.githubusercontent.com/68929218/88731155-0361bc80-d105-11ea-810a-6ff0511a4291.png)

**Comment by DanielS146** [comment]
This also occurs with the repeated tenor field as well.

**Comment by karend27** [comment]
I'm going to close this since "Load my Work" is no longer a functionality in the new code (which saves work differently). However, will still keep an eye on what happens in the folio box of diva.js when navigating through different parts of the interface.
