### ISSUE TITLE
Add a mechanism to allow the user to return to the input editor

### ISSUE THREAD

**Issue by martha-thomae** [MeasuringPolyphony/mp_editor#4]
Already in the "Score Editor", the user might realize that s/he missed something when entering the notes in the "Input Editor" (something present in the original image: a staff, note, etc.) and might want to go back to fix that.

A button (or another mechanism) to allow the user to return to the "Input Editor" might be useful.

**Comment by JRegimbal** [comment]
I'm working on adding this functionality just by using the back button in the browser. Currently the staves will stay and diva should continue to work, but the metadata will need to be entered again.

Would this be sufficient?

**Comment by martha-thomae** [comment]
For now, seems sufficient. Thanks for adding this!

**Comment by karend27** [comment]
Back button works well. Closing this issue.
