### ISSUE TITLE
Currently not possible to only delete a dot in Music Input 

### ISSUE THREAD

**Issue by zenkuriyama** [MeasuringPolyphony/mp_editor#43]
In Music Input, it is currently not possible to just delete a dot in Music Input. For example, in the screenshotted example, if I wanted to delete that dot, I would also have to delete the pitches that follow it. 

![Screen Shot 2020-08-03 at 2 40 05 PM](https://user-images.githubusercontent.com/68929218/89215779-3ab5ea80-d597-11ea-97cb-4519af5aaa8d.png)

**Comment by karend27** [comment]
I'm going to close this - I think our general principle is that in the music input there are certain things that will cause you to just have to delete and re-enter a staff and that it's not possible to edit dots in the music input stage. You can however edit them in the score editor.
