### ISSUE TITLE
Deleting Notes in Score Editor

### ISSUE THREAD

**Issue by DanielS146** [MeasuringPolyphony/mp_editor#53]
If too many notes are deleted in Score Editor, an error message is received and the program crashes.
![Too Many Deleted Notes in Score Editor](https://user-images.githubusercontent.com/69400378/89719008-e6917880-d991-11ea-93e8-ede8cf1e082f.JPG)

**Comment by karend27** [comment]
I think this is an issue we resolve with an update in our documentation letting users know if they try to delete too many notes in score editor it will cause problems and their best solution is to return to music input, and delete the staff and reenter it.
