### ISSUE TITLE
Staff Deletion Error

### ISSUE THREAD

**Issue by DanielS146** [MeasuringPolyphony/mp_editor#54]
There is a potential problem with staff deletion. If one chooses the wrong voice part or mensuration and does not catch the error immediately--i.e. a save has been made or one has moved back and forth between Score Editor and Music Input or a new staff has been worked on--the staff can be visually deleted but still remains when transcribed into Score Editor. This leads to staves being doubled, tripled, etc. whereby the corrected staff is simply added to the voice part in Score Editor instead of replacing the deleted staff. 
![Doubling 1](https://user-images.githubusercontent.com/69400378/89719205-f14d0d00-d993-11ea-9a55-526ba915f7a9.JPG)
![Doubling 2](https://user-images.githubusercontent.com/69400378/89719210-f316d080-d993-11ea-9807-84fc7ef1e36f.JPG)
![Doubling 3](https://user-images.githubusercontent.com/69400378/89719212-f611c100-d993-11ea-8ecb-0dccd9748a13.JPG)

[Firmissime-Adesto Staff Replication Error Console Logs.log](https://github.com/MeasuringPolyphony/mp_editor/files/5046174/Firmissime-Adesto.Staff.Replication.Error.Console.Logs.log)

**Comment by DanielS146** [comment]
In relation to this Issue, if you delete a staff immediately after entering the notes, then this is not a problem. But, once you possibly save your work, move back and forth between Music Input and Score Editor, and/or work on a new staff, you have to click on the “Delete Staff” button multiple times before it is visually removed. However, that deleted staff remains due to the problem detailed in the main part of this Issue.

**Comment by DanielS146** [comment]
I am not sure if this is related to this post, but here is another example from a different piece where all highlighted staves were inexplicably doubled when transcribed into Score Editor. However, in this case, no deletion occurred beforehand. 

[Ne pensez pas Console Logs Doubling Error.log]
(https://github.com/MeasuringPolyphony/mp_editor/files/5072033/Ne.pensez.pas.Console.Logs.Doubling.Error.log)
[Ne pensez pas MEI Parts and Score Doubling Error.zip](https://github.com/MeasuringPolyphony/mp_editor/files/5072034/Ne.pensez.pas.MEI.Parts.and.Score.Doubling.Error.zip)

**Comment by karend27** [comment]
This appears to be fixed in the new version. Tested today.
