### ISSUE TITLE
Support for corrections in the Score Editor

### ISSUE THREAD

**Issue by martha-thomae** [MeasuringPolyphony/mp_editor#6]
Add support for making corrections in the Score Editor (especially, adding dots) and for **re-running the "scoring-up script" afterwards**. 

These edits in the score would correct errors present in the original images (scribal errors present in the manuscript), not errors made during user entry. 

Being able to select a note and add a **dot** to it, or select a note and change its note-shape are some of the basic corrections needed.

**Comment by JRegimbal** [comment]
As of commit 3d2dbd42add63 dots can be added/removed from the score editor by clicking on a note and pressing `.`. Scoring-up will be run automatically after.

**Comment by JRegimbal** [comment]
It's now possible to also change the duration of a selected note using the same mapping as in the input editor and to adjust the pitch of a note by using the up and down arrow keys.

**Comment by JRegimbal** [comment]
Added the following features:
.
- Editing accidentals using the same controls as the input editor;
- Cloning a note by selecting it and pressing `I`; and
- Deleting a note by selecting it and pressing `Backspace`.

**Comment by karend27** [comment]
Nice - these all work well!
