### ISSUE TITLE
Alignment Issues (Ars Nova)

### ISSUE THREAD

**Issue by DanielS146** [MeasuringPolyphony/mp_editor#60]
Below, you will find an example of some of the alignment issues that I ran into while transcribing the ars nova piece, "Ne pensez pas" (MEI files and Console logs included as well).

![Ne pensez pas Alignment Issues Edited](https://user-images.githubusercontent.com/69400378/91300940-18685480-e772-11ea-9d5e-880d7dc4184a.JPG)
[Ne pensez pas MEI Score.zip](https://github.com/MeasuringPolyphony/mp_editor/files/5129646/Ne.pensez.pas.MEI.Score.zip)
[Ne pensez pas Console Logs.log](https://github.com/MeasuringPolyphony/mp_editor/files/5129647/Ne.pensez.pas.Console.Logs.log)

**Comment by martha-thomae** [comment]
Hi @DanielS146!
Sorry, I guess I don't see it. I guess the red lines are pointing to notes that should line up. 
So, the first semibreve marked in the image in the upper voice is imperfecting the breve, isn't it?
And in the lower voice there are only 3 semibreves between those breves, so the first breve should be kept perfect. That is why the C4 semibreve is lined up with the last beat of the breve below, and then the semibreve rests (in both voices) are lined up. Is there a dot of division missing or something?

**Comment by DanielS146** [comment]
Thank you for taking the time to look this over. This would seem to be an instance of human error on my part. There are 2 other instances in this ballade of Machaut ignoring Franco's rules in the spirit of the ars nova, but I seem to have missed this one and interpreted it as a program error. Also, the final misalignment is due to a missing semibreve that is supposed to precede the final long in the cantus.
