### ISSUE TITLE
Parts are displayed in wrong order in score editor

### ISSUE THREAD

**Issue by karend27** [MeasuringPolyphony/mp_editor#65]
The parts are displayed in the order triplum, tenor, motetus, but they should be displayed as triplum, motetus, tenor. Attaching the MEI parts and MEI score file downloaded from the score editor screen.

[Archive 4.zip](https://github.com/MeasuringPolyphony/mp_editor/files/5176683/Archive.4.zip)

**Comment by JRegimbal** [comment]
Is there a set order of parts that should always be followed?

**Comment by karend27** [comment]
I could give you a few usual scenarios:

quadruplum
triplum
duplum/motetus
tenor
contratenor

cantus
tenor
contratenor

superius/discantus/cantus
altus/quintus
tenor
contratenor
bassus

uppervoice I
uppervoice II
tenor
contratenor

triplum
motetus
lower voice I
lower voice II

(these are instances where you might have pairs of voices - common in English music - but they haven't necessarily been labeled).

**Comment by JRegimbal** [comment]
This should be fixed now due to that last commit.

**Comment by karend27** [comment]
Thanks!
