### ISSUE TITLE
Parts-based and Score-based files downloaded have different IDs

### ISSUE THREAD

**Issue by JRegimbal** [MeasuringPolyphony/mp_editor#7]
Currently the button to save the parts-based MEI file and the button to move to the score editor each generate separate MEI files. Even if no editor actions have occurred between these two button clicks, the `xml:id` values will be different for *all* elements.

**Comment by martha-thomae** [comment]
@JRegimbal, I think this issue might need to be re-opened. When I see the files Karen sent today (the repeated tenor files), the corresponding elements have different XML IDs.

**Comment by JRegimbal** [comment]
Hmm if she got them from different pages (input editor and score editor) then that's to be expected. If they were both from the score editor, then that is a problem.

**Comment by karend27** [comment]
I would ignore these files - I think the parts file I got by going back to parts after the score and then downloading. I will do this again tomorrow and resend you the files.


Sent from Yahoo Mail for iPad


On Monday, April 20, 2020, 11:26 AM, martha-thomae <notifications@github.com> wrote:




@JRegimbal, I think this issue might need to be re-opened. When I see the files Karen sent today (the repeated tenor files), the corresponding elements have different XML IDs.
