### ISSUE TITLE
Validation Errors in Score and Parts File

### ISSUE THREAD

**Issue by martha-thomae** [MeasuringPolyphony/mp_editor#72]
There are just a few more validation errors in the score file (I couldn't see them before because we weren't exporting a score when we were looking into the file with the metadata issues). The remaining validation issues are:
- [x] The attribute `@meiversion` in the `<mei>` root element should have a value `"5.0.0-dev"` according to the schema version being used (dev/mei-Mensural.rng).
- [x] `<label>` should be the first child of `<staffDef>` (at least, it should go before `<mensur>`)
- [x] `@dots` are not valid attributes of `<note>` or `<rest>` elements

**Comment by martha-thomae** [comment]
The first one (the mei version issue) is affecting both the parts-based and the score-based MEI file.

**Comment by martha-thomae** [comment]
Oh, and the issue with the 5.0.0 version happened because it was recently decided that the development version was going to be v5.0 (rather than 4.0.1, as it was a few days ago)

**Comment by martha-thomae** [comment]
Forgot to include that the second issue in the checking list is for me :) 
(because it happens during the transformation from parts to score)

**Comment by karend27** [comment]
Hi @martha-thomae and @JRegimbal - is this issue fixed? I'll close the issue if it is.

**Comment by martha-thomae** [comment]
I think this is done :)
