### ISSUE TITLE
Support for intermediate saving

### ISSUE THREAD

**Issue by JRegimbal** [MeasuringPolyphony/mp_editor#8]
The editing process in the input and score editors may go on for a while, but cannot be saved in any form. The [Storage API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API) should be used to allow a set number of possible intermediates be stored between sessions.

- [x] Input Editor
- [ ] Score Editor

**Comment by JRegimbal** [comment]
Input editor saving/loading should now work.

**Comment by martha-thomae** [comment]
Just checked it. Perfect, thanks!

**Comment by karend27** [comment]
I'm going to close this also - the loading/saving/downloading options I think combine to make this very usable.
