### ISSUE TITLE
When adding text in data input screen, backspacing to delete text does not seem to work

### ISSUE THREAD

**Issue by karend27** [MeasuringPolyphony/mp_editor#9]

**Comment by JRegimbal** [comment]
Hmm that's strange. Was the note you wanted to add text to selected?

**Comment by karend27** [comment]
I think I had possibly done too many things. I did eventually figure out backspacing to delete the text. Perhaps close this ticket for now and I will see if it’s possible to recreate what I did.


Sent from Yahoo Mail for iPad


On Thursday, March 19, 2020, 4:54 PM, Juliette Regimbal <notifications@github.com> wrote:




Hmm that's strange. Was the note you wanted to add text to selected?
